import { useEffect, useMemo, useState } from "react";
import { optimizeToolCall } from "@cutdex/core";
import Account from "./Account";

type Bench = { costReductionPercent: number; toolTokenReductionPercent: number; taskSuccessDelta: number; sampleCount: number; baselinePassed: number; optimizedPassed: number; dataReductionPercent: number };
const fallback: Bench = { costReductionPercent: 65.6, toolTokenReductionPercent: 65.6, taskSuccessDelta: 0, sampleCount: 120, baselinePassed: 115, optimizedPassed: 115, dataReductionPercent: 65.6 };
const sampleTask = "Find the five most recent failed orders";
const sampleQuery = "SELECT * FROM orders;";
const apiSnippet = ["const optimized = await fetch(", "  \"https://siftline-omega.vercel.app/api/v1/optimize\",", "  {", "    method: \"POST\",", "    headers: {", "      Authorization: `Bearer ${CUTDEX_API_KEY}`,", "      \"Content-Type\": \"application/json\"", "    },", "    body: JSON.stringify({ task, tool, request })", "  }", ");"].join("\n");

function Number({ value, suffix = "%" }: { value: number; suffix?: string }) { return <>{value.toFixed(1)}{suffix}</> }

export default function App() {
  const [bench, setBench] = useState<Bench>(fallback);
  const [task, setTask] = useState(sampleTask);
  const [query, setQuery] = useState(sampleQuery);
  useEffect(() => { fetch("/latest.json").then((res) => res.ok ? res.json() : fallback).then((value: Bench) => setBench(value)).catch(() => undefined) }, []);
  const result = useMemo(() => optimizeToolCall({ task, tool: { name: "database.query", kind: "READ", readOnly: true }, request: { query } }), [task, query]);
  if (window.location.pathname === "/benchmarks") return <Benchmarks bench={bench} />;
  if (window.location.pathname === "/account") return <Account />;
  return <main>
    <Header />
    <section className="hero wrap"><div className="hero-copy-block"><h1>Cut Codex Usage by <strong><Number value={bench.toolTokenReductionPercent} /></strong></h1><p><strong>Cutdex reduces unnecessary Codex tool output before it reaches your context, cutting token usage while keeping the information Codex actually needs to work.</strong></p><div className="hero-links"><a className="primary-link" href="/account">Get an API key <span>↗</span></a><a href="#connect">See the connection <span>↓</span></a></div></div><TerminalArt /></section>
    <section className="truth wrap"><h2>What it actually changes</h2><div className="truth-grid"><div><strong>Before</strong><code>SELECT * FROM orders;</code><span>Illustration: 42 fields × 1,000 rows</span></div><div className="rewrite-arrow">→</div><div><strong>After</strong><code>SELECT id, status, created_at<br />FROM orders<br />WHERE status = 'failed'<br />ORDER BY created_at DESC<br />LIMIT 5;</code><span>3 fields × 5 rows</span></div></div><p>Cutdex reduces tool-result input sent to the model. It does not make model reasoning, code generation, or built-in tools cheaper unless those reads are routed through Cutdex.</p></section>
    <section className="connect wrap" id="connect"><h2>Connect a coding agent in three commands.</h2><div className="steps"><div><b>1</b><div><h3>Create a key</h3><p>Sign in with Google and create up to three revocable API keys.</p><code>open siftline-omega.vercel.app/account</code></div></div><div><b>2</b><div><h3>Log the CLI in</h3><p>The key is verified, then stored locally with owner-only file permissions.</p><code>npx cutdex@latest login</code></div></div><div><b>3</b><div><h3>Register the optimizer</h3><p>Codex starts Cutdex as an MCP server. The key stays in the CLI config.</p><code>cutdex connect codex</code></div></div></div><div className="connection-note"><strong>For Codex</strong><p>The MCP tool explicitly optimizes broad read calls, then Codex executes the smaller request with the original source tool. The response omits the duplicate original request to keep the optimizer itself cheap. It cannot silently intercept Codex’s built-in shell, browser, or filesystem tools.</p><strong>For custom agents</strong><p>Call <code>POST /api/v1/optimize</code> as middleware immediately before executing a read-only tool request.</p></div></section>
    <section className="pipeline wrap"><h2>The request gets smaller before the result exists.</h2><div className="pipeline-line"><span>Agent task</span><i>→</i><span>Broad tool call</span><i>→</i><strong>Cutdex API</strong><i>→</i><span>Narrow source query</span><i>→</i><span>Smaller result</span></div><div className="api-example"><pre>{apiSnippet}</pre><div><h3>API behavior</h3><p>Keys are hashed before storage. Each key has an atomic per-minute and monthly quota. Writes and unknown operations pass through unchanged.</p><a href="https://github.com/TaxCollector23/siftline/blob/main/docs/api.md">Read the API contract ↗</a></div></div></section>
    <section className="benchmark-run wrap"><strong>Synthetic fixture run</strong><span><Number value={bench.dataReductionPercent} /> less returned data</span><span>{bench.sampleCount} tasks</span><span>{bench.taskSuccessDelta.toFixed(1)}pp success change</span><a href="/benchmarks">Methodology →</a></section>
    <p className="benchmark-caveat wrap">This is an estimate from deterministic fixtures—not proof of lower provider billing or more subscription usage. Your result depends on which reads are routed and how broad their original requests are.</p>
    <section className="playground wrap" id="playground"><div className="play-head"><h2>See a request shrink.</h2><p>This demo runs locally in the browser. No key or model call.</p></div><div className="play-grid"><label>Task<textarea value={task} onChange={(event) => setTask(event.target.value)} /></label><label>Original tool call<textarea value={query} onChange={(event) => setQuery(event.target.value)} /></label><div className="output"><div className="output-top"><span>Optimized request</span><span>{result.safety === "safe" ? "Narrowed safely" : "Passed through"}</span></div><pre>{result.optimizedRequest.query}</pre><div className="explain-list">{result.applied.length ? result.applied.map((item) => <div key={item.name}><b>{item.name}</b><span>{item.reason}</span></div>) : <div><b>PASS THROUGH</b><span>{result.explanation[0] ?? "No safe transformation found."}</span></div>}</div></div></div></section>
    <section className="safety wrap"><h2>Safety is the first optimization.</h2><div><article><h3>Reads only by default</h3><p>Writes and unknown operations are not rewritten.</p></article><article><h3>Every change is inspectable</h3><p>Projection, filter, sort, and limit passes include concrete reasons.</p></article><article><h3>Ambiguity passes through</h3><p>If parsing or confidence fails, the original request survives.</p></article></div></section>
    <section className="closing wrap"><h2>Route one broad read through Cutdex. Measure what comes back.</h2><div><a className="primary-link" href="/account">Create an API key <span>↗</span></a><a href="https://github.com/TaxCollector23/siftline">Inspect the source <span>↗</span></a></div></section>
    <Footer />
  </main>;
}

function Header() { return <header className="wrap site-header"><a className="brand" href="/">cutdex<span>_</span></a><nav><a href="/#connect">connect</a><a href="/#playground">playground</a><a href="/benchmarks">benchmark</a><a href="https://github.com/TaxCollector23/siftline">github ↗</a></nav></header> }
function Footer() { return <footer className="wrap footer"><span>© 2026 Cutdex</span><span>source-side request optimization</span><span>MIT</span></footer> }
function TerminalArt() { return <div className="terminal-art" aria-label="Cutdex CLI setup example"><div className="terminal-bar"><span>terminal</span><span>● ● ●</span></div><pre><span className="terminal-prompt">$</span> npx cutdex@latest{`\n\n`}<span className="terminal-orange">╭──────────────────────────────╮{`\n`}│  Cutdex                     │{`\n`}│  source-side optimizer       │{`\n`}╰──────────────────────────────╯</span>{`\n\n`}<span className="terminal-prompt">$</span> cutdex login{`\n`}Paste your API key: <span className="terminal-muted">••••••••••••</span>{`\n`}Verified. Next: cutdex connect codex{`\n\n`}<span className="terminal-prompt">$</span> cutdex connect codex{`\n`}MCP registered. Restart Codex.</pre></div> }
function Benchmarks({ bench }: { bench: Bench }) { return <main><Header /><section className="bench-page wrap"><h1>Benchmark methodology, without the marketing shortcut.</h1><p className="hero-copy">This is a deterministic synthetic suite of {bench.sampleCount} tasks. It measures request and fixture-result reduction—not a customer’s actual model bill.</p><div className="bench-table"><div><span>Estimated fixture cost reduction</span><strong><Number value={bench.costReductionPercent} /></strong></div><div><span>Synthetic result reduction</span><strong><Number value={bench.dataReductionPercent} /></strong></div><div><span>Task-success delta</span><strong>{bench.taskSuccessDelta.toFixed(1)}pp</strong></div><div><span>Quality gate</span><strong>{bench.taskSuccessDelta >= -1 ? "PASS" : "FAIL"}</strong></div></div><div className="method"><h2>How it is produced</h2><div><p>The baseline executes each broad fixture request. Cutdex applies conservative source-side narrowing, then compares bytes, approximate model-facing tokens, and deterministic task outcomes. Pricing is illustrative and simulated usage is labeled as estimated.</p><p>The suite does not prove that you will receive more Codex or ChatGPT subscription usage. Real savings require an instrumented adapter and before/after provider usage.</p><a className="primary-link" href="https://github.com/TaxCollector23/siftline/blob/main/benchmarks/results/latest.md">Open the generated report <span>↗</span></a></div></div></section><Footer /></main> }
