import { useEffect, useMemo, useState } from "react";
import { optimizeToolCall } from "@siftline/core";
import Account from "./Account";

type Bench = { costReductionPercent: number; toolTokenReductionPercent: number; taskSuccessDelta: number; sampleCount: number; baselinePassed: number; optimizedPassed: number; dataReductionPercent: number };
const fallback: Bench = { costReductionPercent: 65.6, toolTokenReductionPercent: 65.6, taskSuccessDelta: 0, sampleCount: 120, baselinePassed: 115, optimizedPassed: 115, dataReductionPercent: 65.6 };
const sampleTask = "Find the five most recent failed orders";
const sampleQuery = "SELECT * FROM orders;";
const apiSnippet = ["const { response } = await executeWithCutdex(", "  { task, tool, request },", "  (optimizedRequest) => source.execute(optimizedRequest)", ");", "", "// local optimizer; no model or OpenAI API call"] .join("\n");

function Number({ value, suffix = "%" }: { value: number; suffix?: string }) { return <>{value.toFixed(1)}{suffix}</> }

export default function App() {
  const [bench, setBench] = useState<Bench>(fallback);
  const [task, setTask] = useState(sampleTask);
  const [query, setQuery] = useState(sampleQuery);
  useEffect(() => { fetch("/latest.json").then((res) => res.ok ? res.json() : fallback).then((value: Bench) => setBench(value)).catch(() => undefined) }, []);
  const result = useMemo(() => optimizeToolCall({ task, tool: { name: "database.query", kind: "READ", readOnly: true }, request: { query } }), [task, query]);
  if (window.location.pathname === "/benchmarks") return <Benchmarks bench={bench} />;
  if (window.location.pathname === "/account") return <Account />;
  return <main>
    <Header />
    <section className="hero wrap"><div className="hero-copy-block"><h1>Cut Codex context before it lands.</h1><p><strong>Cutdex is a local request optimizer for Codex tool calls.</strong> It narrows eligible read-only SQL and GraphQL requests before the source returns data, so the Codex client has less tool output to carry forward.</p><div className="hero-links"><a className="primary-link" href="#connect">Install local mode <span>↓</span></a><a href="#billing">See the billing boundary <span>↓</span></a></div></div><TerminalArt /></section>
    <section className="truth wrap"><h2>What it actually changes</h2><div className="truth-grid"><div><strong>Before</strong><code>SELECT * FROM orders;</code><span>Broad source request</span></div><div className="rewrite-arrow">→</div><div><strong>After</strong><code>SELECT id, status, created_at<br />FROM orders<br />WHERE status = 'failed'<br />ORDER BY created_at DESC<br />LIMIT 5;</code><span>Smaller source result</span></div></div><p>Cutdex reduces tool-result context sent to Codex. It does not claim to reduce reasoning, generated output, or unrelated built-in tools.</p></section>
    <section className="billing-boundary wrap" id="billing"><h2>The model stays in your Codex plan.</h2><div className="boundary-grid"><div><strong>Cutdex</strong><p>Runs as a local deterministic optimizer. It makes zero model requests and zero OpenAI API calls.</p></div><div><strong>Codex</strong><p>Continues to execute the task with the account and client you signed into. Verify the active allowance with <code>/status</code>.</p></div><div><strong>Scope</strong><p>Only eligible structured reads are narrowed. Shell, browser, filesystem, reasoning, and other MCP tools are outside this boundary.</p></div></div></section>
    <section className="connect wrap" id="connect"><h2>Connect Codex in two commands.</h2><div className="steps"><div><b>1</b><div><h3>Register the local MCP server</h3><p>No API key is required for the default path.</p><code>npx cutdex@latest connect codex</code></div></div><div><b>2</b><div><h3>Restart Codex and verify</h3><p>Run <code>/mcp</code>, then let Codex call Cutdex before a broad read-only request.</p><code>cutdex doctor</code></div></div></div><div className="connection-note"><strong>Local by default</strong><p>The MCP server computes the rewrite in-process and returns it to Codex. An optional hosted API exists for account quotas, but it is disabled unless <code>CUTDEX_USE_HOSTED_API=1</code>.</p><strong>For custom agents</strong><p>Use <code>executeWithCutdex</code> immediately before your source executor to keep the boundary in one process.</p></div></section>
    <section className="pipeline wrap"><h2>The request gets smaller before the result exists.</h2><div className="pipeline-line"><span>Codex task</span><i>→</i><span>Broad read</span><i>→</i><strong>Cutdex local</strong><i>→</i><span>Narrow source query</span><i>→</i><span>Smaller result</span></div><div className="api-example"><pre>{apiSnippet}</pre><div><h3>Boundary behavior</h3><p>Writes and unknown operations pass through unchanged. The adapter executes only the optimized source request and does not invoke a model.</p><a href="https://github.com/TaxCollector23/siftline/blob/main/docs/api.md">Read the API contract ↗</a></div></div></section>
    <section className="benchmark-run wrap"><strong>Synthetic fixture run</strong><span><Number value={bench.dataReductionPercent} /> less returned data</span><span>{bench.sampleCount} tasks</span><span>{bench.taskSuccessDelta.toFixed(1)}pp success change</span><a href="/benchmarks">Methodology →</a></section>
    <p className="benchmark-caveat wrap">This is an estimate from deterministic fixtures—not a Codex invoice or proof of subscription savings. Measure your own paired traces with <code>cutdex analyze</code>.</p>
    <section className="playground wrap" id="playground"><div className="play-head"><h2>See a request shrink.</h2><p>This demo runs locally in the browser. No key or model call.</p></div><div className="play-grid"><label>Task<textarea value={task} onChange={(event) => setTask(event.target.value)} /></label><label>Original tool call<textarea value={query} onChange={(event) => setQuery(event.target.value)} /></label><div className="output"><div className="output-top"><span>Optimized request</span><span>{result.safety === "safe" ? "Narrowed safely" : "Passed through"}</span></div><pre>{result.optimizedRequest.query}</pre><div className="explain-list">{result.applied.length ? result.applied.map((item) => <div key={item.name}><b>{item.name}</b><span>{item.reason}</span></div>) : <div><b>PASS THROUGH</b><span>{result.explanation[0] ?? "No safe transformation found."}</span></div>}</div></div></div></section>
    <section className="safety wrap"><h2>Safety is the first optimization.</h2><div><article><h3>Reads only by default</h3><p>Writes and unknown operations are not rewritten.</p></article><article><h3>Every change is inspectable</h3><p>Projection, filter, sort, and limit passes include concrete reasons.</p></article><article><h3>Ambiguity passes through</h3><p>If parsing or confidence fails, the original request survives.</p></article></div></section>
    <section className="closing wrap"><h2>Make the read smaller before Codex sees it.</h2><div><a className="primary-link" href="#connect">Install Cutdex <span>↓</span></a><a href="https://github.com/TaxCollector23/siftline">Inspect the source <span>↗</span></a></div></section>
    <Footer />
  </main>;
}

function Header() { return <header className="wrap site-header"><a className="brand" href="/">cutdex<span>_</span></a><nav><a href="/#billing">billing</a><a href="/#connect">connect</a><a href="/#playground">playground</a><a href="/benchmarks">benchmark</a><a href="https://github.com/TaxCollector23/siftline">github ↗</a></nav></header> }
function Footer() { return <footer className="wrap footer"><span>© 2026 Cutdex</span><span>local Codex context optimization</span><span>MIT</span></footer> }
function TerminalArt() { return <div className="terminal-art" aria-label="Cutdex CLI setup example"><div className="terminal-bar"><span>terminal</span><span>● ● ●</span></div><pre><span className="terminal-prompt">$</span> npx cutdex@latest{`\n\n`}<span className="terminal-orange">╭──────────────────────────────╮{`\n`}│  Cutdex                    │{`\n`}│  local Codex optimizer      │{`\n`}╰──────────────────────────────╯</span>{`\n\n`}<span className="terminal-prompt">$</span> cutdex connect codex{`\n`}MCP registered locally. No API key.{`\n\n`}<span className="terminal-prompt">$</span> cutdex doctor{`\n`}Optimizer: local · OpenAI API calls: 0</pre></div> }
function Benchmarks({ bench }: { bench: Bench }) { return <main><Header /><section className="bench-page wrap"><h1>Measure the part Cutdex can change.</h1><p className="hero-copy">This deterministic suite measures request and fixture-result reduction across {bench.sampleCount} tasks. It does not claim lower provider billing or more subscription usage.</p><div className="bench-table"><div><span>Estimated fixture reduction</span><strong><Number value={bench.costReductionPercent} /></strong></div><div><span>Tool-result reduction</span><strong><Number value={bench.dataReductionPercent} /></strong></div><div><span>Task-success delta</span><strong>{bench.taskSuccessDelta.toFixed(1)}pp</strong></div><div><span>Quality gate</span><strong>{bench.taskSuccessDelta >= -1 ? "PASS" : "FAIL"}</strong></div></div><div className="method"><h2>How it is produced</h2><div><p>The baseline executes each broad fixture request. Cutdex applies conservative source-side narrowing, then compares bytes, approximate model-facing tokens, and deterministic task outcomes.</p><p>Pricing is illustrative. A real Codex-plan comparison requires paired traces from the same Codex client and its own usage surface.</p><a className="primary-link" href="https://github.com/TaxCollector23/siftline/blob/main/benchmarks/results/latest.md">Open the generated report <span>↗</span></a></div></div></section><Footer /></main> }
