import { useEffect, useMemo, useState } from "react";
import { optimizeToolCall } from "@cutdex/core";
import Account from "./Account";

type Bench = { toolTokenReductionPercent: number; estimatedContextReductionPercent: number; taskSuccessDelta: number; sampleCount: number; baselinePassed: number; optimizedPassed: number; dataReductionPercent: number; baselineContextTokens: number; cutdexContextTokens: number; estimatedInputCostUsd: { baseline: number; cutdex: number; saved: number; inputPerMillion: number } };
const fallback: Bench = { toolTokenReductionPercent: 81.3, estimatedContextReductionPercent: 81.2, taskSuccessDelta: 0, sampleCount: 120, baselinePassed: 115, optimizedPassed: 115, dataReductionPercent: 81.3, baselineContextTokens: 5383330, cutdexContextTokens: 1012760, estimatedInputCostUsd: { baseline: 16.15, cutdex: 3.04, saved: 13.11, inputPerMillion: 3 } };
const sampleTask = "Find the five most recent failed orders";
const sampleQuery = "SELECT * FROM orders;";

function Number({ value, suffix = "%" }: { value: number; suffix?: string }) { return <>{value.toFixed(1)}{suffix}</> }

export default function App() {
  const [bench, setBench] = useState<Bench>(fallback);
  const [task, setTask] = useState(sampleTask);
  const [query, setQuery] = useState(sampleQuery);
  useEffect(() => { fetch("/latest.json").then((res) => res.ok ? res.json() : fallback).then((value: Partial<Bench>) => setBench({ ...fallback, ...value })).catch(() => undefined) }, []);
  const result = useMemo(() => optimizeToolCall({ task, tool: { name: "database.query", kind: "READ", readOnly: true }, request: { query } }), [task, query]);
  if (window.location.pathname === "/benchmarks") return <Benchmarks bench={bench} />;
  if (window.location.pathname === "/account") return <Account />;
  return <main>
    <Header />
    <section className="hero wrap"><div className="hero-copy-block"><h1>Cut Codex Usage by <strong><Number value={bench.estimatedContextReductionPercent} /></strong></h1><p><strong>Cutdex reduces unnecessary Codex tool output before it reaches your context, cutting token usage while keeping the information Codex actually needs to work.</strong></p><div className="hero-proof"><b><Number value={bench.estimatedContextReductionPercent} /> less measured tool context</b><span>{bench.sampleCount} deterministic cases · {bench.taskSuccessDelta.toFixed(1)}pp task-success change</span></div><div className="hero-links"><a className="primary-link" href="/account">Get an API key <span>↗</span></a><a href="#usage">See run cost <span>↓</span></a></div></div><TerminalArt /></section>
    <section className="truth wrap"><h2>What it actually changes</h2><div className="truth-grid"><div><strong>Before</strong><code>SELECT * FROM orders;</code><span>42 fields × 1,000 rows</span></div><div className="rewrite-arrow">→</div><div><strong>After</strong><code>SELECT id, status, created_at<br />FROM orders<br />WHERE status = 'failed'<br />ORDER BY created_at DESC<br />LIMIT 5;</code><span>3 fields × 5 rows</span></div></div><p>Only read requests are narrowed. Writes, unsupported syntax, and ambiguous tasks pass through unchanged.</p></section>
    <section className="usage-proof wrap" id="usage"><div className="usage-intro"><h2>What the run costs.</h2><p>This 120-case fixture measures the request plus returned result. At the illustrative $<Number value={bench.estimatedInputCostUsd.inputPerMillion} suffix="" /> per million input tokens:</p></div><div className="usage-cards"><div className="usage-card"><span>Without CutDex</span><strong>{bench.baselineContextTokens.toLocaleString()} tokens</strong><small>${bench.estimatedInputCostUsd.baseline.toFixed(2)} input cost</small></div><div className="usage-card usage-card-after"><span>With CutDex</span><strong>{bench.cutdexContextTokens.toLocaleString()} tokens</strong><small>${bench.estimatedInputCostUsd.cutdex.toFixed(2)} input cost</small></div><div className="usage-saved"><span>Measured saving</span><strong>${bench.estimatedInputCostUsd.saved.toFixed(2)}</strong><small>{bench.estimatedContextReductionPercent}% less input context</small></div></div><p className="usage-note">This is not a Codex bill: it excludes system prompts, history, reasoning, generated output, and provider-specific tokenization. For an actual run, compare paired provider usage with <code>cutdex analyze traces.jsonl</code>.</p><div className="usage-loss"><strong>What is lost</strong><span>Only unrequested fields and rows from eligible read results. Writes, reasoning, code generation, and ambiguous calls are not compressed.</span></div></section>
    <section className="connect wrap" id="connect"><h2>Connect Codex in three commands.</h2><div className="steps"><div><b>1</b><div><h3>Create a key</h3><p>Sign in with Google and create a revocable key.</p><code>open siftline-omega.vercel.app/account</code></div></div><div><b>2</b><div><h3>Log the CLI in</h3><p>The key is stored locally with owner-only permissions.</p><code>cutdex login</code></div></div><div><b>3</b><div><h3>Register the optimizer</h3><p>Installs one MCP server and a managed Codex instruction block.</p><code>cutdex connect codex</code></div></div></div><div className="connection-note"><strong>Scope</strong><p>Cutdex runs before read-only tool calls. It cannot intercept Codex’s built-in shell, browser, or filesystem tools; route those through a custom adapter if they return large structured data.</p></div></section>
    <section className="benchmark-run wrap"><strong>Published fixture run</strong><span><Number value={bench.toolTokenReductionPercent} /> fewer tool-result tokens</span><span><Number value={bench.estimatedContextReductionPercent} /> approx. tool context</span><span>{bench.sampleCount} tasks · {bench.taskSuccessDelta.toFixed(1)}pp success change</span><a href="/benchmarks">Methodology →</a></section>
    <section className="playground wrap" id="playground"><div className="play-head"><h2>See a request shrink.</h2><p>This demo runs locally in the browser. No key or model call.</p></div><div className="play-grid"><label>Task<textarea value={task} onChange={(event) => setTask(event.target.value)} /></label><label>Original tool call<textarea value={query} onChange={(event) => setQuery(event.target.value)} /></label><div className="output"><div className="output-top"><span>Optimized request</span><span>{result.safety === "safe" ? "Narrowed safely" : "Passed through"}</span></div><pre>{result.optimizedRequest.query}</pre><div className="explain-list">{result.applied.length ? result.applied.map((item) => <div key={item.name}><b>{item.name}</b><span>{item.reason}</span></div>) : <div><b>PASS THROUGH</b><span>{result.explanation[0] ?? "No safe transformation found."}</span></div>}</div></div></div></section>
    <Footer />
  </main>;
}

function Header() { return <header className="wrap site-header"><a className="brand" href="/">cutdex<span>_</span></a><nav><a href="/#usage">usage</a><a href="/#connect">connect</a><a href="/#playground">playground</a><a href="/benchmarks">benchmark</a><a href="https://github.com/TaxCollector23/siftline">github ↗</a></nav></header> }
function Footer() { return <footer className="wrap footer"><span>© 2026 Cutdex</span><span>source-side request optimization</span><span>MIT</span></footer> }
function TerminalArt() { return <div className="terminal-art" aria-label="CutDex CLI setup example"><div className="terminal-bar"><span>terminal</span><span>● ● ●</span></div><pre><span className="terminal-orange">╭──────────────────────────╮{`\n`}│          CutDex          │{`\n`}│  source-side optimizer   │{`\n`}╰──────────────────────────╯</span>{`\n\n`}<span className="terminal-prompt">$</span> cutdex login{`\n`}<span className="terminal-orange">✓ API key stored locally</span>{`\n\n`}<span className="terminal-prompt">$</span> cutdex connect codex{`\n`}<span className="terminal-orange">✓ MCP + AGENTS.md installed</span></pre></div> }
function Benchmarks({ bench }: { bench: Bench }) { return <main><Header /><section className="bench-page wrap"><h1>Measure the part Cutdex can change.</h1><p className="hero-copy">This deterministic suite measures read-result and request-context reduction across {bench.sampleCount} tasks. It does not claim lower provider billing or more subscription usage.</p><div className="bench-table"><div><span>Tool-result token reduction</span><strong><Number value={bench.toolTokenReductionPercent} /></strong></div><div><span>Approx. tool-context reduction</span><strong><Number value={bench.estimatedContextReductionPercent} /></strong></div><div><span>Task-success delta</span><strong>{bench.taskSuccessDelta.toFixed(1)}pp</strong></div><div><span>Quality gate</span><strong>{bench.taskSuccessDelta >= -1 ? "PASS" : "FAIL"}</strong></div></div><div className="method"><h2>What the number means</h2><div><p>Baseline: {bench.baselineContextTokens.toLocaleString()} measured input-context tokens, about ${bench.estimatedInputCostUsd.baseline.toFixed(2)} at ${bench.estimatedInputCostUsd.inputPerMillion}/M. Cutdex: {bench.cutdexContextTokens.toLocaleString()} tokens, about ${bench.estimatedInputCostUsd.cutdex.toFixed(2)}. Estimated saving: ${bench.estimatedInputCostUsd.saved.toFixed(2)}.</p><p>The context figure excludes system prompts, conversation history, reasoning, generated output, and provider tokenization. Run <code>cutdex analyze traces.jsonl</code> against paired provider traces for actual usage and cost.</p><a className="primary-link" href="https://github.com/TaxCollector23/siftline/blob/main/benchmarks/results/latest.md">Open the generated report <span>↗</span></a></div></div></section><Footer /></main> }
