import { parseSelect, printSelect, type SelectAst } from "./sql.js";
import { optimizeGraphql, printGraphql } from "./graphql.js";
import type { OptimizeInput, OptimizationResult, PassResult } from "./types.js";
const defaultFields = ["id", "status", "total", "created_at"];
const noChange = { bytes: 0, inputTokens: 0, percent: 0, measurement: "no_change" as const, note: "The request was not changed." };
const notMeasured = { bytes: null, inputTokens: null, percent: null, measurement: "not_measured" as const, note: "Siftline did not observe the tool result. Measure before/after result bytes or provider usage in your adapter." };
function hasAny(task: string, words: string[]): boolean { const normalized = task.toLowerCase(); return words.some((word) => normalized.includes(word)) }
function fieldsFromTask(task: string): string[] { const fields = new Set<string>(["id"]); const normalized = task.toLowerCase(); if (hasAny(normalized, ["status", "failed", "open", "state"])) fields.add("status"); if (hasAny(normalized, ["total", "amount", "price", "cost"])) fields.add("total"); if (hasAny(normalized, ["customer", "name"])) fields.add("customer_name"); if (hasAny(normalized, ["error", "reason"])) fields.add("error"); if (hasAny(normalized, ["recent", "newest", "latest", "created"])) fields.add("created_at"); return fields.size === 1 ? defaultFields.slice(0, 3) : [...fields] }
function pass(name: string, before: string, after: string, reason: string, expectedBenefit: string): PassResult { return { name, before, after, reason, expectedBenefit, confidence: "high" } }
function inferLimit(task: string): number | undefined { const match = task.match(/\b(?:five|first|top|last|latest)\s+(\d+)\b/i); if (match) return Number(match[1]); if (/\bfive\b/i.test(task)) return 5; if (/\bten\b/i.test(task)) return 10; return undefined }
function inferWhere(task: string): string[] { const normalized = task.toLowerCase(); const conditions: string[] = []; if (normalized.includes("failed")) conditions.push("status = 'failed'"); else if (normalized.includes("open")) conditions.push("status = 'open'"); if (normalized.includes("enterprise")) conditions.push("customer_tier = 'enterprise'"); if (normalized.includes("security")) conditions.push("label = 'security'"); return conditions }
function normalizeCondition(value: string): string { return value.toLowerCase().replace(/\s+/g, " ").replace(/\s*=\s*/g, "=").trim() }
function optimizeSql(task: string, query: string): { ast: SelectAst; applied: PassResult[]; skipped: PassResult[] } {
  const ast = parseSelect(query); const applied: PassResult[] = []; const skipped: PassResult[] = []; if (!ast) return { ast: { columns: [], table: "", where: [] }, applied, skipped: [pass("PARSE", query, query, "The SQL parser could not establish a safe SELECT AST.", "Preserve the original request")] };
  const original = printSelect(ast);
  if (hasAny(task, ["every field", "all fields", "all columns", "raw export"])) return { ast, applied, skipped: [pass("CONTROL", original, original, "The task explicitly asks for the complete record shape.", "Do not remove requested fields")] };
  if (ast.columns.length === 1 && ast.columns[0] === "*" && !ast.aggregate) { const next = fieldsFromTask(task); ast.columns = next; applied.push(pass("PROJECTION", original, printSelect(ast), `Kept only fields named or implied by the task: ${next.join(", ")}.`, "Fewer fields leave the source and reach the model")) }
  const existingWhere = new Set(ast.where.map(normalizeCondition)); const inferredWhere = inferWhere(task).filter((condition) => !existingWhere.has(normalizeCondition(condition))); if (inferredWhere.length) { const before = printSelect(ast); ast.where = [...ast.where, ...inferredWhere]; applied.push(pass("PREDICATE", before, printSelect(ast), `The task explicitly asks for ${inferredWhere.join(" and ")}.`, "Filter at the source")) }
  if (hasAny(task, ["most recent", "newest", "latest"]) && !ast.orderBy) { const before = printSelect(ast); ast.orderBy = { column: "created_at", direction: "DESC" }; applied.push(pass("SORT", before, printSelect(ast), "The task asks for the newest records.", "Let the source sort before returning rows")) }
  const limit = inferLimit(task); if (limit && ast.limit === undefined) { const before = printSelect(ast); ast.limit = limit; applied.push(pass("LIMIT", before, printSelect(ast), `The task asks for at most ${limit} records.`, "Avoid fetching rows that cannot be used")) }
  return { ast, applied, skipped };
}
export function optimizeToolCall(input: OptimizeInput): OptimizationResult {
  const originalRequest = input.request; const kind = input.tool.kind ?? (input.tool.readOnly ? "READ" : "UNKNOWN");
  if (kind !== "READ" || input.tool.readOnly === false) return { originalRequest, optimizedRequest: originalRequest, applied: [], skipped: [], estimatedSavings: noChange, confidence: "high", safety: "passed-through", explanation: ["Write and unknown tools pass through unchanged."] };
  if (typeof input.request.query !== "string") return { originalRequest, optimizedRequest: originalRequest, applied: [], skipped: [], estimatedSavings: noChange, confidence: "low", safety: "passed-through", explanation: ["Only structured SQL requests are optimized in v1."] };
  if (input.request.query.includes("{") && input.request.query.includes("}")) {
    const graphql = optimizeGraphql(input.task, input.request.query); if (!graphql) return { originalRequest, optimizedRequest: originalRequest, applied: [], skipped: [], estimatedSavings: noChange, confidence: "low", safety: "passed-through", explanation: ["The structured request was already narrow or had no high-confidence field match."] };
    const optimizedRequest = { ...input.request, query: printGraphql(graphql.ast) }; const applied = [{ name: "GRAPHQL_PROJECTION", before: input.request.query, after: optimizedRequest.query, reason: `Kept fields named by the task: ${graphql.selected.join(", ")}.`, confidence: "high" as const, expectedBenefit: "Return a smaller structured object" }]; return { originalRequest, optimizedRequest, applied, skipped: [], estimatedSavings: notMeasured, confidence: "high", safety: "safe", explanation: applied.map((item) => `${item.name}: ${item.reason}`) };
  }
  const result = optimizeSql(input.task, input.request.query); if (!result.applied.length) return { originalRequest, optimizedRequest: originalRequest, applied: [], skipped: result.skipped, estimatedSavings: noChange, confidence: "low", safety: "passed-through", explanation: result.skipped.map((item) => item.reason) };
  const optimizedRequest = { ...input.request, query: printSelect(result.ast) };
  return { originalRequest, optimizedRequest, applied: result.applied, skipped: result.skipped, estimatedSavings: notMeasured, confidence: "high", safety: "safe", explanation: result.applied.map((item) => `${item.name}: ${item.reason}`) };
}
