import { describe, expect, it } from "vitest";
import { optimizeToolCall, parseGraphql, parseSelect } from "./index.js";
describe("cutdex optimizer", () => {
  it("narrows a read-only SQL query", () => { const result = optimizeToolCall({ task: "Find the five most recent failed enterprise orders and show customer name, total and error", tool: { name: "database.query", kind: "READ", readOnly: true }, request: { query: "SELECT * FROM orders" } }); expect(result.optimizedRequest.query).toContain("customer_name"); expect(result.optimizedRequest.query).toContain("LIMIT 5"); expect(result.applied.map((item) => item.name)).toEqual(["PROJECTION", "PREDICATE", "SORT", "LIMIT"]) });
  it("never changes writes", () => { const request = { query: "DELETE FROM orders WHERE status = 'failed'" }; const result = optimizeToolCall({ task: "delete failed orders", tool: { name: "database.query", kind: "WRITE", readOnly: false }, request }); expect(result.optimizedRequest).toEqual(request); expect(result.safety).toBe("passed-through") });
  it("parses select ASTs instead of editing SQL text", () => { expect(parseSelect("SELECT id, title FROM issues WHERE state = 'open' ORDER BY created_at DESC LIMIT 10")).toMatchObject({ table: "issues", limit: 10, orderBy: { direction: "DESC" } }) });
  it("leaves an already-narrow request unchanged", () => { const query = "SELECT id, status, total, created_at FROM payments WHERE status = 'failed' ORDER BY created_at DESC LIMIT 5"; const result = optimizeToolCall({ task: "Find the five most recent failed payments", tool: { name: "database.query", kind: "READ", readOnly: true }, request: { query } }); expect(result.applied).toHaveLength(0); expect(result.optimizedRequest.query).toBe(query); expect(result.estimatedSavings.measurement).toBe("no_change") });
  it("projects a structured GraphQL-style request", () => { const result = optimizeToolCall({ task: "Show issue title and state", tool: { name: "github.searchIssues", kind: "READ", readOnly: true }, request: { query: "query Issues { issues { number title state labels avatarUrl } }" } }); expect(result.optimizedRequest.query).toContain("title"); expect(result.optimizedRequest.query).not.toContain("avatarUrl"); expect(result.applied[0]?.name).toBe("GRAPHQL_PROJECTION") });
  it("preserves the nested GraphQL response shape", () => { const result = optimizeToolCall({ task: "Show issue title and state", tool: { name: "github.searchIssues", kind: "READ", readOnly: true }, request: { query: "query Issues { issues { number title state labels avatarUrl } }" } }); expect(result.optimizedRequest.query).toBe("query Issues {\n  issues {\n    number\n    title\n    state\n  }\n}"); expect(parseGraphql(result.optimizedRequest.query as string)).toMatchObject({ rootField: "issues", fields: ["number", "title", "state"] }); });
  it("passes through deeper GraphQL nesting instead of flattening it", () => { const query = "query Issues { repository { issues { number title state labels } } }"; const result = optimizeToolCall({ task: "Show issue title and state", tool: { name: "github.searchIssues", kind: "READ", readOnly: true }, request: { query } }); expect(result.optimizedRequest).toEqual({ query }); expect(result.safety).toBe("passed-through"); });
  it("keeps unsupported SQL shapes intact", () => { const request = { query: "SELECT * FROM orders UNION SELECT * FROM archived_orders" }; const result = optimizeToolCall({ task: "Find failed orders", tool: { name: "database.query", kind: "READ", readOnly: true }, request }); expect(result.optimizedRequest).toEqual(request); expect(result.safety).toBe("passed-through") });
  it("keeps the projection focused on fields named by the task", () => { const result = optimizeToolCall({ task: "Give me the titles of the first ten open issues", tool: { name: "database.query", kind: "READ", readOnly: true }, request: { query: "SELECT * FROM issues" } }); expect(result.optimizedRequest.query).toContain("title"); expect(result.optimizedRequest.query).toContain("LIMIT 10"); expect(result.optimizedRequest.query).not.toContain("customer_name") });
});
