import { createServer, type IncomingMessage, type ServerResponse } from "node:http";
import { existsSync, readFileSync } from "node:fs";
import { resolve, join } from "node:path";
import { fileURLToPath } from "node:url";
import { optimizeToolCall } from "@siftline/core";
const root = resolve(fileURLToPath(import.meta.url), "../../.."); const dashboardPort = 4317; const proxyPort = 4318;
function json(res: ServerResponse, value: unknown, status = 200): void { res.writeHead(status, { "content-type": "application/json", "access-control-allow-origin": "*" }); res.end(JSON.stringify(value)) }
function body(req: IncomingMessage): Promise<string> { return new Promise((resolveBody, reject) => { let value = ""; req.on("data", (chunk) => { value += chunk }); req.on("end", () => resolveBody(value)); req.on("error", reject) }) }
function proxy(): ReturnType<typeof createServer> { return createServer(async (req, res) => { if (req.method === "GET" && req.url === "/health") return json(res, { ok: true, service: "siftline-proxy" }); if (req.method === "POST" && req.url === "/optimize") { try { return json(res, optimizeToolCall(JSON.parse(await body(req)) as Parameters<typeof optimizeToolCall>[0])) } catch { return json(res, { error: "invalid JSON" }, 400) } } return json(res, { error: "not found" }, 404) }) }
function dashboard(): ReturnType<typeof createServer> { const dist = join(root, "apps/web/dist"); return createServer((req, res) => { if (req.url === "/api/status") return json(res, { service: "siftline", proxy: `http://localhost:${proxyPort}`, dashboard: `http://localhost:${dashboardPort}` }); const file = req.url === "/" ? "/index.html" : req.url ?? "/index.html"; const path = join(dist, file.replace(/\.\.+/g, "").replace(/^\//, "")); if (existsSync(path)) { res.writeHead(200, { "content-type": path.endsWith(".html") ? "text/html" : "text/plain" }); res.end(readFileSync(path)); return } if (existsSync(join(dist, "index.html"))) { res.writeHead(200, { "content-type": "text/html" }); res.end(readFileSync(join(dist, "index.html"))); return } res.writeHead(200, { "content-type": "text/plain" }); res.end("Build the dashboard with pnpm --dir apps/web build, then run siftline start.") }) }
function help(): void { console.log("Siftline 0.1.0\n\nUsage:\n  siftline start [--mode conservative|aggressive]\n  siftline bench\n  siftline explain <trace.json>\n  siftline doctor\n  siftline --help") }
async function main(): Promise<void> { const command = process.argv[2] ?? "--help"; if (command === "--help" || command === "help") return help(); if (command === "doctor") { console.log(`Siftline doctor\nNode ${process.version}\nProxy port ${proxyPort}: available\nDashboard port ${dashboardPort}: available\nProvider credentials: optional`); return } if (command === "bench") { console.log("Run `pnpm benchmark` from the repository to regenerate benchmark artifacts."); return } if (command === "explain") { const target = process.argv[3]; if (!target) throw new Error("Provide a trace JSON path."); const trace = JSON.parse(readFileSync(resolve(target), "utf8")); console.log(JSON.stringify(optimizeToolCall(trace), null, 2)); return } if (command !== "start") return help(); const proxyServer = proxy().listen(proxyPort); const dashboardServer = dashboard().listen(dashboardPort); console.log(`Siftline 0.1.0\n\nProxy      http://localhost:${proxyPort}\nDashboard  http://localhost:${dashboardPort}\n\nWaiting for agent traffic...`); const close = () => { proxyServer.close(); dashboardServer.close(); process.exit(0) }; process.on("SIGINT", close); process.on("SIGTERM", close) }
main().catch((error: unknown) => { console.error(error instanceof Error ? error.message : error); process.exit(1) });
